#Test S3 bucket CloudFormtaion:
Resources:
  HelloBucket:
    Type: AWS::S3::Bucket
    Properties:
        AccessControl: Private
        BucketName: laith-aws-cloud-formation-test-3
        Tags:
          - Key: name
            Value: laith-s3-testing
  MyInstance1:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-2a
      ImageId: ami-00c03f7f7f2ec15c3
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: Test1-ec2
  MyInstance2:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-2b
      ImageId: ami-00c03f7f7f2ec15c3
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: Test1-ec2
